countries = ["italia", "suiça", "alemanha", "inglaterra", "canadá"]
print(countries)
print()
print(sorted(countries))
print(countries)
print()
print(sorted(countries, reverse=True))
print(countries)
print()
countries.reverse()
print(countries)
print()
countries.reverse()
print(countries)
countries.sort()
print(countries)
print()
countries.sort()
print(countries)
countries.sort(reverse=True)
print(countries)